name: Mirror to Org
on:
  push:
    branches: ["**"]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push mirror
        run: |
          git config --global url."https://x-access-token:${{ secrets.ORG_MIRROR_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git remote add org https://github.com/Planary/planary-dashboard.git
          git push org --mirror